routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProgressController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('contacts', 'ContactController');

Route::resource('progresses', 'ProgressController');

Route::get('/contribute', 'ContributeController@index');

Route::get('/contribute/success', 'ContributeController@success');

Route::get('/about', 'HomeController@about');

Route::resource('invoices','InvoiceController');

app/Http/Controllers/ProgressController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Progress;
use App\Contact;

class ProgressController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $progress_values = Progress::all();
        return view('welcome', compact('progress_values'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$this->middleware('auth');
        return view('progress.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'progress' => 'required'
        ]);

        $progress = new Progress([
            'progress' => $request->get('progress')
        ]);

        $progress->save();
        return redirect('/contacts')->with('success','Progress value is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/progress/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <div>
                <a style="margin: 19px;" href="{{ url('contacts') }}" class="btn btn-dark">Back to lists</a>
            </div>
            <h1 class="display-3">Add Progress Value</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('progresses.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="progress_value">ProgressBar Value:</label>
                        <input type="text" class="form-control" name="progress"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add progress</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/progress/index.blade.php
<?php